### ISSUE TITLE
[Issue]: jaas.security.login.config can have creds and path to config file

### ISSUE THREAD

**Issue by ClearJulyComes** [sngular/kloadgen#303]
### What happened?

Expected:
I am using jaas.security.login.config with creds (username, password which contains "/") and Producer works.
Field looks like: org.apache.kafka.common.security.plain.PlainLoginModule required username=user password=pass/word;

Actual:
Because password contains separator char ("/") it's sets as path to config file and script fails.

Maybe  it's need to add different fields to both of them

### KloadGen Version

kloadgen 3.8.2

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by ClearJulyComes** [comment]
We can provide needed changes if this issue make sense

**Comment by jemacineiras** [comment]
Hi @ClearJulyComes,
we are just passing through the content of this field to the context of the publisher. Nowadays, we are not escaping anything, but looks like, seeing your case we should do.
If you want to collaborate, we will accept your changes, just fork the project and open a PR, so we can review the changes and merge them.

Thanks!!

**Comment by davidgarciago** [comment]
Hello @ClearJulyComes ,

I have tried to reproduce the error and i have not been able to do so. The configuration i used was the following:

org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="kloadgen" username="user" password="pass/word";

With the quotation marks i can set any password without the script failing so please, try to use them and let us know if that solves the problem.

Thanks.

**Comment by davidgarciago** [comment]
Hi @ClearJulyComes,

Any news about the problem you mentioned? Did you manage to use any password using quotation marks?

**Comment by davidgarciago** [comment]
Hi @ClearJulyComes,

This issue is going to be closed due to inactivity, please if the error continues showing up it would be great if you open a new one to solve the problem.

Thanks for your time!
