### ISSUE TITLE
[Issue]: KloadGen Jar not working with Jmeter 5.5

### ISSUE THREAD

**Issue by ayshhg** [sngular/kloadgen#323]
### What happened?

I cannot open the example sample JMX file's in my JMeter 5.5. 

Also in addition, I am not able to see any Kloadgen samplers. I followed exactly what is mentioned in the doc.

### KloadGen Version

5.1.6

### Relevant log output

```shell
Cause:
CannotResolveClassException: kafkaheaders.config.com.sngular.kloadgen.KafkaHeadersConfigElement

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree/kafkaheaders.config.com.sngular.kloadgen.KafkaHeadersConfigElement
line number         : 29
version             : 5.5
-------------------------------
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by mseijasm** [comment]
Hi @ayshhg 

Thank you for your collaboration. We are looking at it and we will get back to you as soon as possible.

**Comment by dianaGomezGar** [comment]
Hi @ayshhg, 

I made some changes to our Test-plan examples. You can find the modified .jmx files on the associate branch. 
Please, try to execute them and let us know if they work in your JMeter 5.5.
Thank you.
