### ISSUE TITLE
[Issue]: Field length = 0 only generates numbers between [1,9] range.

### ISSUE THREAD

**Issue by a-garciam** [sngular/kloadgen#336]
### What happened?

When using a [KLG - Value Schema Serializer Config] with a **float** field type and **0** field length I am only getting floats in a limited range between 1 and 9, but should be producing numbers in a wider range.

### KloadGen Version

KLoadGen 5.2.11

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by mseijasm** [comment]
Hi @a-garciam 

Thank you for your collaboration. We are looking at it and we will get back to you as soon as possible.

**Comment by nuriaricofr** [comment]
Hi @a-garciam 
Can you try the "#336_generates_random_float_array" branch to see if it works?

**Comment by a-garciam** [comment]
Thanks for the help @nuriaricofr.

I've tested that new branch, it no longer creates numbers exclusively in range [1,9] but now it only generates numbers with 9 or 10 digits.

Examples are: 453988256, 1598796800, 1003320320...

**Comment by nuriaricofr** [comment]
puedes probar de nuevo?

gracias!

**Comment by a-garciam** [comment]
For the purpose of my use now it works perfectly, but I think it is not the correct behavior yet.

It now generates only _**integers**_ between [1, 999].
