### ISSUE TITLE
[Issue]: ALL produced messages are duplicated in jmeter log file

### ISSUE THREAD

**Issue by Kricket** [sngular/kloadgen#348]
### What happened?

When running a test, KLoadgen echos every single message produced to the log, using level INFO.

This is due to the following line:
https://github.com/sngular/kloadgen/blob/ab4eac46d9615fec1b01a5ae6510b3193a75d06f/src/main/java/com/sngular/kloadgen/sampler/KafkaProducerSampler.java#L140

When running a performance test, this is a huge waste:
* Time spent writing **every single message** to the log file
* Disk space taken up by the huge log file

Would it be possible to either:
1. Use the DEBUG log level here, or
2. Make this log message optional (e.g. via a checkbox in the interface)

### KloadGen Version

5.1.6

### Relevant log output

```shell
2023-03-07 16:11:27,321 INFO o.a.j.p.j.s.AbstractJavaSamplerClient: Send message with key: (blabla) and body: (blabla)
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by dhergonsngular** [comment]
Hi @Kricket 

Thank you for your collaboration. We are looking into it and will get back to you as soon as possible.

**Comment by dhergonsngular** [comment]
Hello @Kricket 

We have applied changes to not show this log information. 
The changes are in the branch #348_remove_unnecessary_log_info. Can you check if it works?
