### ISSUE TITLE
[Issue]: BUILD FAILURE

### ISSUE THREAD

**Issue by kamal2222ahmed** [sngular/kloadgen#386]
### What happened?

after building with skip tests ( as it was not building with tests enabled. I am unable to open ANY of the sample cmx files included in the repository

### KloadGen Version

kloadgen-5.6.3.jar

### Relevant log output

```shell
% jm -t Apicurio-Test-Plan.jmx
WARNING: package sun.awt.X11 not in java.desktop
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/syedahmed/QA/TOOLS/JMETER/JMETER-LOCAL/apache-jmeter-5.5/lib/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/syedahmed/QA/TOOLS/JMETER/JMETER-LOCAL/apache-jmeter-5.5/lib/ext/pepper-box-1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
================================================================================
Don't use GUI mode for load testing !, only for Test creation and Test debugging.
For load testing, use CLI Mode (was NON GUI):
   jmeter -n -t [jmx file] -l [results file] -e -o [Path to web report folder]
& increase Java Heap to meet your test requirements:
   Modify current env variable HEAP="-Xms1g -Xmx1g -XX:MaxMetaspaceSize=256m" in the jmeter batch file
Check : https://jmeter.apache.org/usermanual/best-practices.html
================================================================================
An error occurred: org/reflections/Configuration
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by AdrianLagarteraSngular** [comment]
Thanks for helping us @kamal2222ahmed, first of all I would appreciate if you can add the JMX you are testing to reproduce the problem. 

At first I would think that changing the Jmeter version in the JMX file would be enough, but give me the file anyway in case there is any other extra problem.

**Comment by jemacineiras** [comment]
Hi @kamal2222ahmed,

Do you mind try again without the pepper-box-1.0.jar plugin installed? may be we are dealing with some package conflict here.

Cheers

**Comment by AdrianLagarteraSngular** [comment]
Hi @kamal2222ahmed it's been a while since we have received any updates, by removing the other plugin have you managed to make it work?

**Comment by AdrianLagartera** [comment]
Closed due a no answer in a month, open it again if the same help is needed.
