### ISSUE TITLE
[Issue]: Error with Schema File Serializer / Deserializer

### ISSUE THREAD

**Issue by norangeles162** [sngular/kloadgen#388]
### What happened?

Hello,

   I'm trying to test producer and consumer with schema registry, using KLG - Value Schema File, and Key File.
   From graphic JMeter it does not list the clases for serialize/deserialize when using Value Schema File option, I forced it adding directly from jmx file (because the clases ARE on the kloadgen jar), but in the case of Key Schema File, it does list some classes, but not the ones associated to io.confluent.kafka.serializers and the trick of setting hardcode directly does not work in this case.
     I was able to run the test from no graphic mode without key schema.

<img width="729" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/a3cf2fed-9878-4106-b4a7-aaaed767bf4c">

<img width="575" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/c87ee4c9-0323-4186-856d-0cc421c7affb">

<img width="726" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/fb8dbd83-4d42-41bc-9717-a22a4fb3fed4">

<img width="566" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/c2eba161-f773-4e47-94c6-48bf8f768dfb">

<img width="693" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/59a3e178-cb6e-458f-b400-e7066082c2be">

JMeter 5.5
Java   11.0.2

[SR-PRE-test - kloadgen.zip](https://github.com/sngular/kloadgen/files/11737372/SR-PRE-test.-.kloadgen.zip)

### KloadGen Version

kloadgen-5.6.3

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by jemacineiras** [comment]
Hi @norangeles162.
we take a look closely to this issue and back to you asap.

Cheers!

**Comment by AdrianLagarteraSngular** [comment]
Hi @norangeles162 what OS are you having problems on? I Just download your JMX file and works pretty fine for me, I am using Jmeter 5.5 and the last version of KloadGen too and, I am using MacOS Ventura 13.2.1 (22D68).

<img width="1149" alt="Captura de pantalla 2023-06-13 a las 19 11 00" src="https://github.com/sngular/kloadgen/assets/103184566/218f8f28-0bab-4e2a-998a-4edff5da940e">

<img width="1149" alt="Captura de pantalla 2023-06-13 a las 19 16 36" src="https://github.com/sngular/kloadgen/assets/103184566/b22df4d7-201a-4853-b299-b5f6de9f57e0">

<img width="1147" alt="Captura de pantalla 2023-06-13 a las 19 17 04" src="https://github.com/sngular/kloadgen/assets/103184566/0f36e2ac-1723-4cb2-860d-73ee67ccd8c9">

Btw I just enable the config options you disable, just in case that's the problem, could you try to do a new installation of JMeter? And this happens too if you remove our plugin?

Thank you, we look forward to hearing from you.

**Comment by norangeles162** [comment]
Hello,

   I'm working with "Windows 11 Pro"
   I had try with a new installation of JMeter and it works (now it list the classes), then I compare the directorys of the new installation and the old one, and I could find what the problem was, I had "kafka-clients-3.4.1.jar" inside lib folder, and it seams it doesn't like. You could try to reproduce the error.


<img width="790" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/95e39c84-0e80-4639-b5a9-e3428b13be3f">

<img width="956" alt="image" src="https://github.com/sngular/kloadgen/assets/73830398/582b7856-75cb-4dcd-bf8f-7a301fab5787">

**Comment by AdrianLagarteraSngular** [comment]
Well I didn't saw nothing about the library, and looks like a residual library from another plugin or something like that, thank you for give the details of the library which could cause the problem, I will close the issue because works fine now. 

Again thank you for collaborate with us.
